index commit
CollegeStationCodeSociety/collegestationcodesociety.github.io pull request #9
Opened 2021-05-12 22:36 UTC by anonymoustaco

final (hopefully index commit)

2021-05-13 19:45 UTC, OrdoFlammae requested changes
Looks very nice! Replace `favicon.gif` with `favicon.png` (@KateCat-attempts should be able to provide a conversion), replace the README, and we should be good to go!

2021-05-13 19:45 UTC, OrdoFlammae commented on README.md
> -# collegestationcodesociety.github.io
Could you replace this file?

2021-05-14 12:18 UTC, anonymoustaco commented
here is the commit with favicon in PNG format and READNE added

2021-05-14 17:05 UTC, OrdoFlammae commented
Looks great! Good job @anonymoustaco!

2021-05-14 17:05 UTC, merged